// Firm dataset — converted from outputs/eligibility-dataset-starter.csv
// Fields left null/false where the source CSV marked "TBC - verify" — never guessed.
// classificationRank: null = no confirmed minimum found. Otherwise 4=1st, 3=2:1, 2=2:2, 1=3rd.
const FIRMS = [
  { name: "Sullivan & Cromwell", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Confirmed final-year non-law eligibility for 2026 spring/summer vac schemes.", verified: "partial" },
  { name: "White & Case", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Accepts final-year non-law students and graduates from any discipline.", verified: "partial" },
  { name: "Clyde & Co", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Non-law final-year undergraduates eligible for 2026 summer vac scheme.", verified: "partial" },
  { name: "Reed Smith", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Vac scheme open to non-law students from final year onwards.", verified: "partial" },
  { name: "Clifford Chance", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "PGDL delivered via partnership with University of Law for non-law trainees.", verified: "partial" },
  { name: "A&O Shearman", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Non-law route requires PGDL at BPP specifically.", verified: "partial" },
  { name: "Irwin Mitchell", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Funds PGDL tuition for non-law graduates who haven't started the course yet.", verified: "confirmed" },
  { name: "Slaughter and May", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP required for non-law trainees.", verified: "confirmed" },
  { name: "Linklaters", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP.", verified: "confirmed" },
  { name: "Freshfields Bruckhaus Deringer", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP.", verified: "confirmed" },
  { name: "Herbert Smith Freehills", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP.", verified: "confirmed" },
  { name: "Norton Rose Fulbright", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 10500, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "City Consortium member. Up to 50 TCs/year across two intakes (March & September). PGDL sponsorship + £10,500 grant; SQE sponsorship + £17,000 grant.", verified: "confirmed" },
  { name: "Baker McKenzie", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Confirmed 2-year Training Contract accepts both law and non-law graduates.", verified: "partial" },
  { name: "Hogan Lovells", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Pays PGDL course fees + maintenance grant. PGDL typically starts ~2 years before TC start.", verified: "confirmed" },
  { name: "Eversheds Sutherland", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Explicitly welcomes all degree disciplines.", verified: "partial" },
  { name: "Mishcon de Reya", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Recruits trainees solely through Vacation Scheme. Open to undergrads/grads/postgrads/career-changers, any degree.", verified: "partial" },
  { name: "Addleshaw Goddard", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Requires 2.1 honours degree or equivalent. Open to law/non-law and career changers.", verified: "partial" },
  { name: "Ashurst", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 12000, location: "London", locationTag: "single", deadline: null, notes: "PGDL bursary at University of Law + £12,000 grant (£10,200 outside London).", verified: "confirmed" },
  { name: "Simmons & Simmons", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 13000, location: "London / Bristol", locationTag: "multi", deadline: null, notes: "SQE + PGDL sponsored + £13,000 grant (London) / £11,000 (Bristol).", verified: "confirmed" },
  { name: "DLA Piper", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Funds postgraduate tuition + living cost sponsorship — exact amount not confirmed.", verified: "partial" },
  { name: "Travers Smith", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 13500, location: "London", locationTag: "single", deadline: null, notes: "40%+ of trainees are non-law; genuinely no preference. PGDL fully funded + £13,500 grant.", verified: "confirmed" },
  { name: "Macfarlanes", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 13000, location: "London", locationTag: "single", deadline: null, notes: "Vac scheme from penultimate year (any subject). TC: law from penultimate year, non-law from final year. PGDL funded + £13,000 grant.", verified: "confirmed" },
  { name: "Charles Russell Speechlys", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Minimum 2.1 degree. Explicit non-law policy not directly confirmed — verify.", verified: "unconfirmed" },
  { name: "Gowling WLG", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: 2, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 7000, location: "London / Birmingham", locationTag: "multi", deadline: null, notes: "Accepts 2:2 or below — unusually flexible academic requirement. PGDL/LLM SQE funded + £7,000 grant (London) / £5,500 (Birmingham).", verified: "confirmed" },
  { name: "Shoosmiths", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Non-law route requires PGDL + LLM SQE via BPP partnership. Grant amount not confirmed.", verified: "partial" },
  { name: "Latham & Watkins", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 20000, location: "London", locationTag: "single", deadline: null, notes: "PGDL (8-month course) fully covered + £20,000 maintenance grant — one of the highest found.", verified: "confirmed" },
  { name: "Weil Gotshal & Manges", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 20000, location: "London", locationTag: "single", deadline: null, notes: "PGDL + SQE1&2 fully sponsored via University of Law partnership + £20,000/year grant.", verified: "confirmed" }
];
