// Firm dataset — converted from outputs/eligibility-dataset-starter.csv
// Fields left null/false where unconfirmed — never guessed.
// classificationRank: null = no confirmed minimum found. Otherwise 4=1st, 3=2:1, 2=2:2, 1=3rd.
// applyUrl: direct link to the firm's current training contract / vacation scheme page, verified 2026-08-22.
const FIRMS = [
  { name: "Sullivan & Cromwell", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Confirmed final-year non-law eligibility for 2026 spring/summer vac schemes.", verified: "confirmed", applyUrl: "https://www.sullcrom.com/Careers/Offices/United-Kingdom/U.K.-Trainee-Solicitors-Programme" },
  { name: "White & Case", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Accepts final-year non-law students and graduates from any discipline.", verified: "partial", applyUrl: "https://www.whitecase.com/careers/locations/uk/early-careers/our-offer/training-contracts" },
  { name: "Clyde & Co", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Non-law final-year undergraduates eligible for 2026 summer vac scheme.", verified: "partial", applyUrl: "https://careers.clydeco.com/en/early-careers/united-kingdom/england/training-contracts/" },
  { name: "Reed Smith", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Vac scheme open to non-law students from final year onwards. Firm states exceptional academic ability elsewhere can offset a below-2:1 result.", verified: "confirmed", applyUrl: "https://www.reedsmith.com/en/careers/regions/uk-graduates" },
  { name: "Clifford Chance", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "PGDL delivered via partnership with University of Law for non-law trainees.", verified: "partial", applyUrl: "https://jobs.cliffordchance.com/training-contract-london" },
  { name: "A&O Shearman", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Non-law route requires PGDL at BPP specifically.", verified: "confirmed", applyUrl: "https://careers.aoshearman.com/en/london-training-contract" },
  { name: "Irwin Mitchell", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Funds PGDL tuition for non-law graduates who haven't started the course yet. Confirmed blind screening — no minimum classification.", verified: "confirmed", applyUrl: "https://www.irwinmitchell.com/about-us/careers/training-contracts" },
  { name: "Slaughter and May", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP required for non-law trainees. No classification minimum published on firm's own site.", verified: "confirmed", applyUrl: "https://www.slaughterandmay.com/careers/early-careers/the-training-contract/" },
  { name: "Linklaters", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP. 2:1 minimum per Chambers Student (not directly on firm page).", verified: "partial", applyUrl: "https://www.linklaters.com/en/careers/early-careers/university-and-graduate-opportunities/training-contracts" },
  { name: "Freshfields Bruckhaus Deringer", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP.", verified: "confirmed", applyUrl: "https://www.freshfields.com/en/your-career/united-kingdom/early-careers/trainee-associate-program" },
  { name: "Herbert Smith Freehills", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "City Consortium member — funded PGDL at BPP.", verified: "confirmed", applyUrl: "https://careers.hsfkramer.com/global/en/uk/early-careers/opportunities" },
  { name: "Norton Rose Fulbright", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 10500, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "City Consortium member. Up to 50 TCs/year across two intakes (March & September). PGDL sponsorship + £10,500 grant; SQE sponsorship + £17,000 grant. Firm confirms 2:1 requirement.", verified: "confirmed", applyUrl: "https://www.nortonrosefulbright.com/en-gb/graduates/opportunities/the-training-contract" },
  { name: "Baker McKenzie", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Confirmed 2-year Training Contract accepts both law and non-law graduates, 2:1 or on track.", verified: "confirmed", applyUrl: "https://uk-graduates.bakermckenzie.com/programmes/direct-training-contract/" },
  { name: "Hogan Lovells", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Pays PGDL course fees + maintenance grant. PGDL typically starts ~2 years before TC start. 2:1 predicted or obtained.", verified: "confirmed", applyUrl: "https://ukearlycareers.hlc.com/what-we-offer/london-training-contract" },
  { name: "Eversheds Sutherland", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Explicitly welcomes all degree disciplines. Careers page currently blocks automated verification — details unconfirmed for this pass.", verified: "partial", applyUrl: "https://www.eversheds-sutherland.com/en/united-kingdom/careers/careers-page/students-and-recent-graduates/student-and-graduate-applications" },
  { name: "Mishcon de Reya", opportunityTypes: ["vac_scheme"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "London", locationTag: "single", deadline: null, notes: "Recruits trainees solely through Vacation Scheme. Open to undergrads/grads/postgrads/career-changers, any degree. Typically expects 2:1 but notes flexibility.", verified: "partial", applyUrl: "https://www.mishcon.com/graduates" },
  { name: "Addleshaw Goddard", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Requires 2.1 honours degree or equivalent (will consider 2:2 with mitigating circumstances). Open to law/non-law and career changers.", verified: "confirmed", applyUrl: "https://earlycareers.addleshawgoddard.com/careers/training-contracts/" },
  { name: "Ashurst", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 12000, location: "London", locationTag: "single", deadline: null, notes: "PGDL bursary at University of Law + £12,000 grant (£10,200 outside London).", verified: "confirmed", applyUrl: "https://www.ashurstperkinscoie.com/en/careers/students-and-graduates/uk-london-training-contract/" },
  { name: "Simmons & Simmons", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 13000, location: "London / Bristol", locationTag: "multi", deadline: null, notes: "SQE + PGDL sponsored + £13,000 grant (London) / £11,000 (Bristol). TC only available after completing the firm's vacation scheme.", verified: "confirmed", applyUrl: "https://www.simmons-simmons.com/en/graduates" },
  { name: "DLA Piper", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Funds postgraduate tuition + living cost sponsorship — exact amount not confirmed. Recruits primarily via summer internship route.", verified: "partial", applyUrl: "https://careers.dlapiper.com/early-careers/europe/uk/international-graduate-programme.html" },
  { name: "Travers Smith", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 13500, location: "London", locationTag: "single", deadline: null, notes: "40%+ of trainees are non-law; genuinely no preference. PGDL fully funded + £13,500 grant. Confirmed 2:1 minimum.", verified: "confirmed", applyUrl: "https://www.traverssmith.com/join-us/early-careers/faq/" },
  { name: "Macfarlanes", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 13000, location: "London", locationTag: "single", deadline: null, notes: "Vac scheme from penultimate year (any subject). TC: law from penultimate year, non-law from final year. PGDL funded + £13,000 grant. Confirmed 2:1 minimum.", verified: "confirmed", applyUrl: "https://www.macfarlanes.com/join-us/early-careers/early-careers-faqs/" },
  { name: "Charles Russell Speechlys", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: null, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Minimum 2.1 degree. Confirmed: welcomes applications from both law and non-law graduates.", verified: "confirmed", applyUrl: "https://www.charlesrussellspeechlys.com/en/careers/early-talent/uk-graduate-opportunities/training-contracts/" },
  { name: "Gowling WLG", opportunityTypes: ["vac_scheme", "training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 7000, location: "London / Birmingham", locationTag: "multi", deadline: null, notes: "Confirmed: no minimum A-Level or degree classification requirement. PGDL/LLM SQE funded + £7,000 grant (London) / £5,500 (Birmingham).", verified: "confirmed", applyUrl: "https://gowlingwlg.com/en/careers/uk/early-talent/training-contracts" },
  { name: "Shoosmiths", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: null, maintenanceGrant: null, location: "Multiple UK offices", locationTag: "multi", deadline: null, notes: "Non-law route requires PGDL + LLM SQE via BPP partnership. Grant amount not confirmed. 2:1 minimum per FAQ page.", verified: "partial", applyUrl: "https://www.shoosmiths.com/careers/emerging-talent/training-contract" },
  { name: "Latham & Watkins", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: 3, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 20000, location: "London", locationTag: "single", deadline: null, notes: "PGDL (8-month course) fully covered + £20,000 maintenance grant — one of the highest found. Recruits exclusively via vacation scheme. Confirmed 2:1 minimum.", verified: "confirmed", applyUrl: "https://www.lwcareers.com/en/beginning-your-legal-career/united-kingdom/how-to-apply" },
  { name: "Weil Gotshal & Manges", opportunityTypes: ["training_contract"], degreeType: "both", classificationRank: null, pgdlRequired: true, pgdlFunded: true, maintenanceGrant: 20000, location: "London", locationTag: "single", deadline: null, notes: "PGDL + SQE1&2 fully sponsored via University of Law partnership + £20,000/year grant.", verified: "confirmed", applyUrl: "https://ukrecruiting.weil.com/training-contract" }
];
